---
ansible_user: root

is_create_initial_admin_data: false
is_create_sample_data: True
is_create_allinone: True

ip_port:
  - 5000/tcp
  - 35357/tcp
  - 3306/tcp
  - 4444/tcp
  - 4567/tcp
  - 4568/tcp

keystone:
  region: RegionOne
  service_name: keystone
  publicurl: "http://{{ hostvars[groups['global_keystone_serv'][0]].svmng }}:5000/v3"
  adminurl: "http://{{ hostvars[groups['global_keystone_serv'][0]].svmng }}:35357/v3"
  internalurl: "http://{{ hostvars[groups['global_keystone_serv'][0]].svint }}:5000/v3"
  admin:
    user_name: admin
    password: xxxx_keystone_user_pass
    project: admin
    role: admin
    domain_id: default
  api_version: 3
  token:
    cron_flush:
      minute: 0
      hour: 0

keystone_db:
  host:
    host: "{{ hostvars[groups['global_keystone_serv'][0]].svmng }}"
    login_user: root
    login_password: xxxx
  db:
    name: keystone
    user: keystone
    password: xxxx_keystone_user_pass

galera:
  host:
    host: "{{ hostvars[groups['global_keystone_serv'][0]].svint }}"
    access_host: localhost
    login_user: root
    login_password: xxxx
  db:
    - create_user_name: root
      name: '*'
      host: '%'
      password: xxxx
    - create_user_name: test
      name: '*'
      host: '%'
      password: xxxx

mariadb_datadir: /mnt/nas01/data/mysql/

backup:
  db:
    name: keystone

galera_cluster:
  cluster_name: my_galera_mariadb_cluster
  cluster_master_node: "{{ hostvars[groups['global_keystone_serv'][0]].svint }}"
  cluster_other_nodes:
    - "{{ hostvars[groups['global_keystone_serv'][0]].svint }}"

# sample role
sample:
  role:
    dc_name: DC1
