---
ansible_user: xxxx

ip_port:
  - 3306/tcp
  - 4444/tcp
  - 4567/tcp
  - 4568/tcp

mariadb_datadir: /mnt/nas01/data/mysql

backup:
  db:
    name: aflo

db_setting:
  - host:
      login_user: root
      login_password: 'xxxx'
    db:
      name: aflo
      user: aflo
      password: xxxx
    userhost:
      - 127.0.0.1
      - '%'
      - localhost
  - host:
      login_user: root
      login_password: 'xxxx'
    db:
      name: drupal
      user: drupal
      password: xxxx
    userhost:
      - '%'
