---
ansible_user: xxxx

is_create_aflo_user: False
is_create_aflo_endpoint: True
is_use_rabbitmq_aflo: True
is_create_sample_workflow_data: True

region_type: region

ap_path: /usr/share

ip_port:
  - 9294/tcp
  - 5672/tcp
  - 4369/tcp
  - 25672/tcp
  - 15672/tcp

aflo_db:
  host:
    host: "{{ hostvars[groups['region_biz_db'][0]].svint }}"
  db:
    name: aflo
    user: aflo
    password: xxxx

aflo:
  service_name: region_ticket
  endpoint:
    - interface: admin
      url: "http://{{ hostvars[groups['region_biz_serv'][0]].svint }}:9294/"
      region: RegionOne
    - interface: public
      url: "http://{{ hostvars[groups['region_biz_serv'][0]].svint }}:9294/"
      region: RegionOne
    - interface: internal
      url: "http://{{ hostvars[groups['region_biz_serv'][0]].svint }}:9294/"
      region: RegionOne
  region_name_list:
    - DC1
  role_name_list:
    - ServiceProvider
    - ServiceManager
    - ContractManager
  disinherited_users:
    - aflo
    - admin
    - cinder
    - ceilometer
    - swift
    - nova
    - glance
    - neutron
    - heat
    - keystone
    - aodh
    - gnocchi

rabbitmq:
  master_node: xxxx
  port: 5672
  nodes:
    - name: xxxx
      addr: "{{ hostvars[groups['region_biz_serv'][0]].svint }}"
      port: 5672
    - name: xxxx
      addr: "{{ hostvars[groups['region_biz_serv'][0]].svint }}"
      port: 5672
  erlang_cookie: xxxx
  user:
    name: guest
    pass: xxxx
  notification_exchange: aflo

keystone:
  identity_uri: "http://{{ hostvars[groups['global_keystone_serv'][0]].svmng }}:35357"
  api_version: 3
  auth_url: "http://{{ hostvars[groups['global_keystone_serv'][0]].svmng }}:5000/v3"
  admin:
    user_name: admin
    password: xxxx_keystone_user_pass
    region_name: RegionOne
    tenant_name: admin
    tenant_id: xxxx_keystone_tenant_id
    user_domain_id: default
    project_domain_id: default
    roles:
      - _member_
      - admin
      - O__DC1__ServiceProvider
  aflo:
    user_name: aflo
    password: xxxx
    tenant_list:
      - admin
      - services
  capacity:
    user_name: nova
    password: xxxx_capacity_user_pass
    region_name: RegionOne
    tenant_name: services
    user_domain_id: default
    project_domain_id: default

mail:
  encode: utf-8
  from_address: ""
  smtp_server: ""
  user: ""
  password: "xxxx"

announcement:
  announcement_url: "https://{{ hostvars[groups['region_cms_serv'][0]].svmng }}"

ost_contract:
  ost_roles: T__DC1__ObjectStore

# sample workflow data
sample:
  aflo_data:
    region:
      - sample_insert_contract_workflow.sql
      - sample_insert_catalog.sql
      - sample_insert_flatrate_contract.sql
      - sample_insert_payforuse_contract.sql
      - sample_insert_change_contract.sql
      - sample_insert_objectstorage_contract.sql
    global:
      - sample_insert_project_contract.sql
      - sample_insert_add_announcement.sql
      - sample_insert_inquiry.sql
    role:
      dc_name: DC1
      service:
        - O__DC1__ServiceManager
      contract:
        - O__DC1__ContractManager
      system:
        - O__DC1__ServiceProvider
      member:
        - T__DC1__ProjectMember
