---
- name: Remove region portal menu(Horizon Menu)
  lineinfile:
    dest: "/usr/share/openstack-dashboard/openstack_dashboard/enabled/{{ item }}"
    state: present
    line: REMOVE_PANEL = True
  with_items:
    - _1450_project_loadbalancers_panel.py
    - _1460_project_firewalls_panel.py
    - _1470_project_vpn_panel.py
    - _1920_project_containers_panel.py
  when: region == 'region' and is_remove_menu

- name: Remove region portal identity menu(Horizon Menu)
  lineinfile:
    dest: "/usr/share/openstack-dashboard/openstack_dashboard/enabled/{{ item }}"
    state: present
    line: REMOVE_PANEL = True
  with_items:
    - _3030_identity_users_panel.py
    - _3040_identity_groups_panel.py
    - _3050_identity_roles_panel.py
  when: region == 'region' and is_remove_menu

- name: Remove global portal menu(Horizon Menu)
  lineinfile:
    dest: "/usr/share/openstack-dashboard/openstack_dashboard/enabled/{{ item }}"
    state: present
    line: REMOVE_PANEL = True
  with_items:
    - _1020_project_overview_panel.py
    - _1030_project_instances_panel.py
    - _1040_project_volumes_panel.py
    - _1050_project_images_panel.py
    - _1060_project_access_panel.py
    - _1420_project_network_topology_panel.py
    - _1430_project_network_panel.py
    - _1440_project_routers_panel.py
    - _1450_project_loadbalancers_panel.py
    - _1460_project_firewalls_panel.py
    - _1470_project_vpn_panel.py
    - _1620_project_stacks_panel.py
    - _1630_project_resource_types_panel.py
    - _1640_project_template_versions_panel.py
    - _1920_project_containers_panel.py
    - _2020_admin_overview_panel.py
    - _2030_admin_metering_panel.py
    - _2040_admin_hypervisors_panel.py
    - _2050_admin_aggregates_panel.py
    - _2060_admin_instances_panel.py
    - _2070_admin_volumes_panel.py
    - _2080_admin_flavors_panel.py
    - _2090_admin_images_panel.py
    - _2100_admin_networks_panel.py
    - _2110_admin_routers_panel.py
    - _2111_admin_floating_ips_panel.py
    - _2120_admin_defaults_panel.py
    - _2130_admin_metadata_defs_panel.py
  when: region == 'global' and is_remove_menu

- name: Change default panel for announcement
  lineinfile:
    dest: "/usr/share/openstack-dashboard/openstack_dashboard/enabled/_2020_admin_overview_panel.py"
    state: present
    regexp: "DEFAULT_PANEL.*"
    line: "DEFAULT_PANEL = 'info'"
  when: region == 'global' and is_remove_menu

- name: Remove neccs menu
  lineinfile:
    dest: "/usr/share/openstack-dashboard/openstack_dashboard/local/enabled/{{ item }}"
    state: present
    line: REMOVE_PANEL = True
  with_items:
    - _2152_admin_add_infrastructure_log_panel.py
    - _2310_admin_capacity_group_nec.py
    - _2320_admin_capacity_capacity_panel_nec.py
  when: region == 'global' and is_remove_menu

- name: Remove price menu
  lineinfile:
    dest: "/usr/share/openstack-dashboard/openstack_dashboard/local/enabled/{{ item }}"
    state: present
    line: REMOVE_PANEL = True
  with_items:
    - _5010_project_add_private_price_lists_panel.py
    - _6010_admin_add_private_price_lists_panel.py
  when: region == 'global' and is_remove_menu

- name: Update _32_fixed_region.py
  lineinfile:
    dest: "/etc/openstack-dashboard/local_settings.d/_32_fixed_region.py"
    state: present
    regexp: "^FIXED_REGION_NAME.*"
    line: "FIXED_REGION_NAME = '{{ keystone.region_name }}'"
  when: is_fix_region
