---
- name: Remove rabbitmq-server
  file:
    path: /etc/logrotate.d/rabbitmq-server
    state: absent

- name: Create dailyRotateRabbitmq
  template:
    src: dailyRotateRabbitmq.j2
    dest: /etc/logrotate.d/dailyRotateRabbitmq
