---
- name: Install packages
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items:
    - name: gcc
      state: present
    - name: python-devel
      state: present
    - name: python-pbr
      state: latest
    - name: openssl-devel
      state: latest

- name: Copy pip install script
  copy:
    src: get-pip.py
    dest: /tmp/

- name: Install pip(Use proxy)
  command: 'python /tmp/get-pip.py --proxy={{ proxy }}'
  when: proxy is defined

- name: Install pip(No use proxy)
  command: python /tmp/get-pip.py
  when: proxy is not defined

- name: Upgrade pip(Use proxy)
  command: 'pip install --upgrade pip --proxy={{ proxy }}'
  when: proxy is defined

- name: Upgrade pip(No use proxy)
  command: pip install --upgrade pip
  when: proxy is not defined
