---
- name: python-Afloclient
  unarchive:
    src: python-Afloclient.tar.gz
    dest: /root/

- name: NECCS python-Afloclient remove
  file:
    path: /usr/share/python-Afloclient
    state: absent

- name: NECCS python-Afloclient Move
  command: mv /root/python-Afloclient.git /usr/share/python-Afloclient

- name: Install python package(Use proxy)
  command: 'pip install -r /usr/share/python-Afloclient/requirements.txt --proxy={{ proxy }}'
  when: proxy is defined

- name: Install python package(No use proxy)
  command: pip install -r /usr/share/python-Afloclient/requirements.txt
  when: proxy is not defined

- name: python-Afloclient python setup
  command: chdir=/usr/share/python-Afloclient/ python setup.py install
