---
# Remove unnecessary horizon & neccs menu
is_remove_menu: True

is_setting_ssl: True
is_setting_httpd: True
is_fix_region: True

# horizon memcached servers
horizon_caches_server:
  - 127.0.0.1
  - 127.0.0.2
fqdn_domain: example.com

region: region

# IaaS policy
policy:
  region_name: DCX

# Proxy
proxy: http://192.168.0.1:8080

ap_path: /usr/share
python_directory: /usr/lib/python2.7

ip_port:
  - 443/tcp
  - 80/tcp

# ssl
ssl_crt_dir: /etc/httpd/conf/ssl.crt
ssl_key_dir: /etc/httpd/conf/ssl.key
ssl_crt_file: server.crt
ssl_key_file: server.key

process_message_file:
  lang_list:
    - en
    - ja
  file_list:
    - django.po
    - djangojs.po
  aflo:
    - lines: 1,16d
      lang: ja
      file: django.po
    - lines: 1,18d
      lang: ja
      file: djangojs.po
    - lines: 1,16d
      lang: en
      file: django.po
    - lines: 1,18d
      lang: en
      file: djangojs.po
  announcement:
    - lines: 1,5d
      lang: ja
      file: django.po
    - lines: 1,5d
      lang: en
      file: django.po
  self_identity:
    - lines: 1,18d
      lang: ja
      file: django.po

aflo:
  service_name: ticket
  region_name_list:
    - DCX
  role_name_list:
    - ServiceProvider

# keystone
keystone:
  host: 192.168.0.1
  auth_url: http://192.168.0.1:5000/v3
  region_name: RegionDCX
  default_role: _member_
  admin:
    username: admin
    password: xxxx
    project_name: admin

announcement:
  url: https://drupalxx.xx/drupal/?q=user/login&destination=top
  url_logout: https://drupalxx.xx/drupal/?q=user/logout

kibana_url:
  portal: https://portalkibanaxx.xx/
  elk: https://kibanaxx.xx/

links:
  admin:
    - name: Global Portal
      url: https://globalportalxx.xx/
      description: To access the Global Portal.
    - name: monitor
      url: http://zabbixwebxx.xx/zabbix/
      description: Do monitered management.
      role: O__DCX__ServiceProvider
    - name: repository
      url: https://gitlabxx.xx/
      description: Do centralized management of resource files.
      role: O__DCX__ServiceManager
    - name: Announce
      url: https://drupalxx.xx/drupal/?q=user/login
      description: Announcement Management
  project:
    - name: Global Portal
      url: https://globalportalxx.xx/
      description: To access the Global Portal.
    - name: repository
      description: Do centralized management of resource files.
      url: https://gitlabxx.xx/
      role: C__Global__ProjectAdmin,T__DCX__ProjectMember

control_admin_menu_roles:
  - admin

is_use_aflo: true
is_use_self_identity: true
is_use_announcement: true
is_use_cinder_backup: false

# Set a keystone role name for object storage
object_storage_admin_role: T__DCX__ObjectStore
