---
- name: Start firewalld
  service:
    name: firewalld
    state: started

- name: Reload firewalld setting
  command: firewall-cmd --reload
  changed_when: false

- name: Set firewall
  command: firewall-cmd --add-port={{ item }} --zone=public
  changed_when: false
  ignore_errors: yes
  always_run: yes
  with_items:
    - "{{ ip_port }}"

- name: Set firewall(permanent)
  command: firewall-cmd --permanent --add-port={{ item }} --zone=public
  changed_when: false
  ignore_errors: yes
  always_run: yes
  with_items:
    - "{{ ip_port }}"

- name: Show firewall list
  command: firewall-cmd --list-all --zone=public

- name: Reload firewall
  command: firewall-cmd --reload
