---
- name: Backup keystone.conf
  command: >
    cp -p
    /etc/keystone/keystone.conf
    /etc/keystone/keystone.conf.org
  args:
    creates: /etc/keystone/keystone.conf.org
    removes: /etc/keystone/keystone.conf

- name: Create keystone.conf
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
    owner: root
    group: keystone
    mode: 0644

- name: Backup httpd.conf
  command: >
    cp -p
    /etc/httpd/conf/httpd.conf
    /etc/httpd/conf/httpd.conf.org
  args:
    creates: /etc/httpd/httpd.conf.org
    removes: /etc/httpd/httpd.conf

- name: Create httpd.conf
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644

- name: Create keystone_wsgi.conf
  template:
    src: keystone_wsgi.conf.j2
    dest: /etc/httpd/conf.d/keystone_wsgi.conf
    owner: root
    group: root
    mode: 0644

- name: Backup policy.json
  command: >
    cp -p
    /etc/keystone/policy.json
    /etc/keystone/policy.json.org
  args:
    creates: /etc/keystone/policy.json.org
    removes: /etc/keystone/policy.json

- name: Create policy.json
  template:
    src: policy.json.j2
    dest: /etc/keystone/policy.json
    owner: keystone
    group: keystone
    mode: 0644

- name: Start keystone
  service:
    name: httpd
    state: started
    enabled: yes

- name: Sync DB
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone
  when: is_master

- name: Restart keystone
  service:
    name: httpd
    state: restarted

- name: Register cron of token_flush
  cron:
    name: keystone flush tokens
    state: present
    minute: "{{ keystone.token.cron_flush.minute }}"
    hour: "{{ keystone.token.cron_flush.hour }}"
    user: keystone
    job: "/usr/bin/keystone-manage token_flush >/dev/null 2>&1"
