---
- name: Create config directory
  file:
    path: /etc/logstash/conf.d
    owner: root
    group: root
    state: directory
    recurse: yes
    mode: u=rwx,g=rx,o=rx

- name: Create portal_history_log.conf
  template:
    src: portal_history_log.conf.j2
    dest: /etc/logstash/conf.d/portal_history_log.conf

- name: Create patterns directory
  file:
    path: /opt/logstash/patterns
    owner: logstash
    group: logstash
    state: directory
    recurse: yes
    mode: u=rwx,g=rx,o=rx

- name: Copy grok-patterns
  copy:
    src: grok-patterns
    owner: logstash
    group: logstash
    dest: /opt/logstash/patterns/

- name: Copy portal_pattern
  copy:
    src: portal_pattern
    owner: logstash
    group: logstash
    dest: /opt/logstash/patterns/

- name: Create log directory
  file:
    path: /var/log/logstash
    owner: logstash
    group: logstash
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create logstash_parse.err
  file:
    path: /var/log/logstash/logstash_parse.err
    owner: logstash
    group: logstash
    state: touch
    mode: 0666

- name: Start services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - logstash
  ignore_errors: yes
